services:

  # =========================================================
  # PRIMARY (MASTER - WRITE)
  # =========================================================
  postgres-primary:
    image: postgres:18
    container_name: pg-primary
    restart: always
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_password
      POSTGRES_DB: quarkus_db
    command: >
      postgres
        -c listen_addresses='*'
        -c wal_level=replica
        -c max_wal_senders=10
        -c max_replication_slots=10
        -c hot_standby=on
        -c hba_file=/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    volumes:
      - pg_primary_data:/var/lib/postgresql
      - ./src/main/resources/init-primary.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    networks:
      - quarkus-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quarkus_user -d quarkus_db" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # =========================================================
  # REPLICA (SLAVE - READ)
  # =========================================================
  postgres-replica:
    image: postgres:18
    container_name: pg-replica
    restart: always
    depends_on:
      postgres-primary:
        condition: service_healthy
    environment:
      POSTGRES_USER: quarkus_user
      POSTGRES_PASSWORD: quarkus_password
      POSTGRES_DB: quarkus_db
      PGPASSWORD: replicator_password
      PGDATA: /var/lib/postgresql/18/main
    entrypoint: [ "bash", "/docker-entrypoint-replica.sh" ]
    ports:
      - "5433:5432"
    volumes:
      - pg_replica_data:/var/lib/postgresql
      - ./src/main/resources/init-replica.sh:/docker-entrypoint-replica.sh
    networks:
      - quarkus-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U quarkus_user -d quarkus_db" ]
      interval: 5s
      timeout: 5s
      retries: 15

  # =========================================================
  # QUARKUS API (NATIVE MODE)
  # =========================================================
  quarkus-api:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.native-multistage
    container_name: quarkus-api
    restart: on-failure
    depends_on:
      postgres-primary:
        condition: service_healthy
      postgres-replica:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Datasource primário (escrita)
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://pg-primary:5432/quarkus_db
      QUARKUS_DATASOURCE_USERNAME: quarkus_user
      QUARKUS_DATASOURCE_PASSWORD: quarkus_password
      # Datasource réplica (leitura)
      QUARKUS_DATASOURCE_LEITURA_REACTIVE_URL: postgresql://pg-replica:5432/quarkus_db
      QUARKUS_DATASOURCE_LEITURA_USERNAME: quarkus_user
      QUARKUS_DATASOURCE_LEITURA_PASSWORD: quarkus_password
    deploy:
      resources:
        limits:
          memory: 128m
        reservations:
          memory: 32m
    networks:
      - quarkus-net
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/q/health/live || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  pg_primary_data:
  pg_replica_data:


networks:
  quarkus-net:
    driver: bridge
